config/routes.rb
Rails.application.routes.draw do
  get 'map/index'

  get 'shops/:id' => 'shops#show'

  get '/' => 'hello#view'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def view
    #render text: 'こんにちは、世界！'
    @msg = 'Hello 世界！！！'
  end
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  def index
    @users = User.new
    @hash = Gmaps4rails.build_markers(@users) do |user, marker|
      marker.lat user.latitude
      marker.lng user.longitude
      marker.json({title: user.title})
    end
  end
end

class User
  def initialize()
    @latitude = 35.1814464
    @longitude = 136.906398
    @title = '名古屋の場所'    
  end
  attr_accessor :latitude, :longitude, :title 
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def show
    @shop = DammyShopInfo.new
  end
end

# 仮データクラス(あとで消すよ)
class DammyShopInfo
  def initialize()
    @name = 'ビストロ・タッキー'
    @genre = 'イタリアン'
    @shop_info = 'あの滝田シェフが手がけるイタリアンが南青山に進出！'
    @image0 = 'shop1.png'
    @image1 = 'food1.png'
    @image2 = 'food2.png'
    @image3 = 'food3.png'
    @image4 = 'food4.png'
    @business_time = 'ランチ 　11:00〜15:00(L.O 14:30)¥nディナー　18:00〜24:00(L.O 23:30)'
    @shop_holiday = '日曜・祝日'
    @address = '東京都港区南青山X-XXX-X'
    @link1 = 'https://www.google.co.jp/'
    @link2 = 'http://www.yahoo.co.jp/'
    @link3 = 'http://www.biglobe.ne.jp/'
  end

  attr_accessor :name, :genre, :shop_info, :image0, :image1, :image2, :image3, :image4, :business_time, :shop_holiday, :address, :link1, :link2, :link3
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/hello/view.html.erb
<div>
  <%= @msg %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hoge</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">
  <script src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/map/index.html.erb
<h1>Map#index</h1>
<p>Find me in app/views/map/index.html.erb</p>
<div class="container">
  <div id="map" style='width: 300px; height: 300px;'></div>
</div>
<p><%= link_to '戻る', '/shops/1' %></p>

<script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers(<%=raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
    });
</script>

app/views/shops/show.html.erb
<style>
  hr{
    margin: 0px;
    height: 5px;
    background-color: orange;
  }
  div.row{
    margin-top: 5px;
  }
  div.row>div{
    padding-right: 5px;
    padding-left: 5px;
  }
  div.col{
    padding-left: 5px;
    padding-right: 5px;
  }
  th{
    background-color: orange;
    color: white;
  }
</style>

<div class="container">
  <%# 店舗名 %>
  <div class="row">
    <div class="col-xs-12">
      <h3><%= @shop.name %>　<small><%= @shop.genre %></small></h3>
    </div>
  </div>
  <hr>
  <%# メイン画像　サイズとかあとで考える %>
  <div class="row">
    <div class="col-xs-12">
      <%= image_tag @shop.image0, class: 'img-responsive' %>
    </div>
  </div>

  <%# サブ画像 　サイズとかあとで考える%>
  <div class="row">
    <div class="col-xs-3">
      <%= image_tag @shop.image1, class: 'img-responsive' %>
    </div>
    <div class="col-xs-3">
      <%= image_tag @shop.image2, class: 'img-responsive' %>
    </div>
    <div class="col-xs-3">
      <%= image_tag @shop.image3, class: 'img-responsive' %>
    </div>
    <div class="col-xs-3">
      <%= image_tag @shop.image4, class: 'img-responsive' %>
    </div>
  </div>

  <%# メニュー・チェックインボタン %>
  <div class="row">
    <div class="col-xs-6">
      <!-- <button class="btn btn-warning btn-block">メニュー 一覧</button> -->
      <%= link_to 'メニュー 一覧', '/shops/1' , class: 'btn btn-warning btn-block' %>
    </div>
    <div class="col-xs-6">
      <!-- <button class="btn btn-success btn-block">このお店にチェックイン</button> -->
      <%= link_to 'このお店にチェックイン', '/', class: 'btn btn-success btn-block' %>
    </div>
  </div>

  <%# 地図・電話 %>
  <div class="row">
    <div class="col-xs-6">
      <%# 地図表示できるようにする %>
      <!-- <button class="btn btn-warning btn-block">地図</button> -->
      <%= link_to '地図', map_index_path, class: 'btn btn-warning btn-block' %>
    </div>
    <div class="col-xs-6">
      <%# 電話アプリ立ち上がるようにする %>
      <button class="btn btn-warning btn-block">電話</button>
    </div>
  </div>

  <%# 店舗説明 %>
  <div class="row">
    <div class="col-xs-12">
      <p><%= @shop.shop_info %></p>
    </div>
  </div>

  <%# その他店舗情報 %>
  <div class="row">
    <div class="col-xs-12">
      <table class="table table-bordered">
        <tbody>
          <tr>
            <th class="col-xs-3">営業時間</th>
            <%# 改行できるようにする、、、 %>
            <td class="col-xs-9"><%= @shop.business_time %></td>
          </tr>
          <tr>
            <th class="col-xs-3">定休日</th>
            <td class="col-xs-9"><%= @shop.shop_holiday %></td>
          </tr>
          <tr>
            <th class="col-xs-3">住所</th>
            <td class="col-xs-9"><%= @shop.address %></td>
          </tr>
          <tr>
            <th class="col-xs-3">外部リンク</th>
            <td class="col-xs-9"></td>
          </tr>
        </tbody>
      </table> 
    </div>
  </div>
</div>